title: Marcell Hermawan Kristianto
description: Data Science student and aspiring AI Engineer based in Jakarta.
url: "https://marknshoot.github.io"
baseurl: "/portofolio"
timezone: Asia/Jakarta
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
safe: false
lsi: false